-- Create the book_a_demo table to store form submissions
CREATE TABLE IF NOT EXISTS public.book_a_demo (
    id bigint generated by default as identity primary key,
    full_name text not null,
    mobile text not null,
    email text not null,
    company text,
    address text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security) and add policies if necessary
ALTER TABLE public.book_a_demo ENABLE ROW LEVEL SECURITY;

-- Allow public inserts
CREATE POLICY "Allow public insert to book_a_demo" ON public.book_a_demo FOR INSERT WITH CHECK (true);

-- Allow authenticated/service to read
CREATE POLICY "Allow select for authenticated" ON public.book_a_demo FOR SELECT USING (true);
